In [2]:
import numpy as np

In [5]:
X = np.array([[1,0,1], [1,1,1], [1,1,-1], [-1,1,1]])
y = np.array([2,2.7, -0.7, 2])
theta = np.array([0,1,2])

R = (1/4)*np.sum(y - np.matmul(X, theta.T))

In [38]:
z = y - np.matmul(X, theta.T)
z[z >= 1] = 0
z[z < 1] = 1 - z[z < 1]
np.mean(z)

In [45]:
z = y - np.matmul(X, theta.T)

np.mean((z ** 2)/2.0)

0.1475

In [48]:
x1 = np.array([1,0,0])
x2 = np.array([0,1,0])
z = x1-x2
(-1/2)*np.linalg.linalg.norm(z)**2

-1.0000000000000002

In [28]:
a =np.diag(np.ones(2))


In [14]:
np.

array([[2., 0.],
       [0., 2.]])

In [16]:
np.sum(a == a)

4

In [19]:
a = np.zeros(5)
b = np.ones(5)


np.mean(a==a)

1.0

In [27]:
for c in range(1,10+1):
    print(c/10)

0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1.0


In [74]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [76]:
np.sum(a**2)

30

In [34]:
np.sum(a, axis=1)

array([3, 7])

In [36]:
a*2

array([[2, 4],
       [6, 8]])

In [37]:
a = np.ones(3)

In [63]:
b =a.reshape(1, 3)
b

array([[1., 1., 1.]])

In [64]:
c = np.repeat(b, 4, axis=0)
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
d = np.diag([1,2,3])
d

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [86]:
g = np.matmul(c, d)
g

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [107]:
idx = np.array([[0,0], [0,1]])


(2, 2)

In [129]:
g_ = g.reshape(4, 3, 1)
g_

array([[[1.],
        [2.],
        [3.]],

       [[1.],
        [2.],
        [3.]],

       [[1.],
        [2.],
        [3.]],

       [[1.],
        [2.],
        [3.]]])

In [130]:
g_.shape

(4, 3, 1)

In [131]:
g_[1,0,2]

IndexError: index 2 is out of bounds for axis 2 with size 1

In [132]:
g - g_

ValueError: operands could not be broadcast together with shapes (4,3) (4,3,1) 

In [58]:
2/np.ones(3)

array([2., 2., 2.])

In [59]:
np.sum(d, axis=0)

array([1, 2, 3])

In [60]:
np.exp(d)

array([[ 2.71828183,  1.        ,  1.        ],
       [ 1.        ,  7.3890561 ,  1.        ],
       [ 1.        ,  1.        , 20.08553692]])

In [71]:
s = "'akin'"
'\033[1;32m%s\033[m' % s

"\x1b'akin'\x1b[m"

In [109]:
import scipy.sparse as sparse

In [111]:
sparse.coo_matrix(([1]*3, (5, range(3))), shape=(3,3))

TypeError: len() of unsized object

In [248]:
def with_sparse(indices, k):
    n = len(indices)
    M = sparse.coo_matrix(([1]*n, (indices, range(n))), shape=(k,n)).toarray()
    return M

In [249]:
N=10
K=10
Y = [3, 4, 1, 2, 8, 4, 1, 7, 2, 3]
with_sparse(Y, K)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [250]:
Y

[3, 4, 1, 2, 8, 4, 1, 7, 2, 3]

In [259]:
labels = np.array([1,2,3,4,7])
n = len(labels)
k = 8
sparse.coo_matrix(([1]*n, (labels, range(n))), shape=(k, n)).toarray()

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1]])

5

### broadcasting

In [261]:
x = np.array([1,2,3,4,5,6]).reshape(2,3) # n by d
p = np.array([1,2,3,4,5,6]).reshape(3,2) # k by n
#t = np.array()
x

array([[1, 2, 3],
       [4, 5, 6]])

In [264]:
type(x)

numpy.ndarray

In [220]:
p

array([[1, 2],
       [3, 4],
       [5, 6]])

In [230]:
p = p.reshape(3,2,1)
p # k by n by 1

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [231]:
c = x*p
c # k by n by d

array([[[ 1,  2,  3],
        [ 8, 10, 12]],

       [[ 3,  6,  9],
        [16, 20, 24]],

       [[ 5, 10, 15],
        [24, 30, 36]]])

In [232]:
c.shape

(3, 2, 3)

In [234]:
z = np.sum(c, axis=1)
z # k by d

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [235]:
z.shape

(3, 3)

In [211]:
c[0]

array([[0, 1, 2],
       [2, 3, 4]])

In [3]:
a = np.array([1,2,3,4,5,6]).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
b = np.array([1,2])
b

array([1, 2])

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b.reshape(3,1)

array([[1],
       [2],
       [3]])

In [22]:
a * b.reshape(2,1)

array([[ 1,  2,  3],
       [ 8, 10, 12]])

In [23]:
a,b

(array([[1, 2, 3],
        [4, 5, 6]]), array([1, 2]))

In [24]:
c = np.array([1,2,3,4]).reshape(2,2)
c

array([[1, 2],
       [3, 4]])

In [32]:
d = a == 2

In [33]:
d+1

array([[1, 2, 1],
       [1, 1, 1]])

In [34]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
c

array([[1, 2],
       [3, 4]])

In [41]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
d = np.array([1,2]).reshape(2,1)
d

array([[1],
       [2]])

In [44]:
d == j

array([[ True, False, False],
       [False, False, False]])

In [54]:
e = np.array([2,2]).reshape(1,2)
e

array([[2, 2]])

In [55]:
d == e

array([[False, False],
       [ True,  True]])

In [61]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
c

array([[1, 2],
       [3, 4]])

In [66]:
a - c

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [84]:
(d == np.arange(9))

array([[False,  True, False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False, False]])

In [78]:
e = np.array([1,2,3]).reshape(1, -1)
f = np.array([1,2,3]).reshape(-1, 1)

In [81]:
np.int32(f == e)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [83]:
(np.arange(9) == d)

array([[False,  True, False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False, False]])

In [86]:
e

array([[1, 2, 3]])

In [88]:
f == e

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [89]:
e == f

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [92]:
e == d

array([[ True, False, False],
       [False,  True, False]])

In [93]:
d == e

array([[ True, False, False],
       [False,  True, False]])

In [95]:
d, e

(array([[1],
        [2]]), array([[1, 2, 3]]))

In [97]:
e.T == d.reshape(1,2)

array([[ True, False],
       [False,  True],
       [False, False]])

In [124]:
(np.arange(100000000).reshape(-1,1) == np.arange(3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       ...,
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [106]:
np.arange(3).shape

(3,)

In [107]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
b.reshape(2, 1)

array([[1],
       [2]])

In [111]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [112]:
a - c

array([[0, 0, 0],
       [3, 3, 3]])

In [123]:
np.equal(np.arange(100000000).reshape(-1,1), np.arange(3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       ...,
       [False, False, False],
       [False, False, False],
       [False, False, False]])